example:
  property: "I AM IN THE DEFAULT"

spring:
  h2:
    console:
      enabled: "true"
      path: "/h2"
  datasource:
    url: "jdbc:h2:file:~/booking_in_memory"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"